### ISSUE TITLE
Permissions issue on `logging.conf` (pyaircontrol.py)

### ISSUE THREAD

**Issue by CatalinMustata** [NikDevx/homebridge-philips-air#165]
So, after a bit of runaround, I've managed to properly install the plugin and airctrl (took me awhile to figure out my unit does not work with http, but CoAP).

Now, at startup I get this error:
```
[4/11/2021, 8:25:37 PM] Error: Command failed: python3 /usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py --ipaddr 192.168.0.100 --protocol coap --status
Traceback (most recent call last):
  File "/usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 8, in <module>
    from pyairctrl.coap_client import CoAPAirClient
  File "/usr/lib/python3.9/site-packages/pyairctrl/coap_client.py", line 14, in <module>
    from coapthon.client.helperclient import HelperClient
  File "/usr/lib/python3.9/site-packages/coapthon/client/helperclient.py", line 7, in <module>
    from coapthon.client.coap import CoAP
  File "/usr/lib/python3.9/site-packages/coapthon/client/coap.py", line 25, in <module>
    create_logging()
  File "/usr/lib/python3.9/site-packages/coapthon/utils.py", line 129, in create_logging
    with open("logging.conf", "w") as f:
PermissionError: [Errno 13] Permission denied: 'logging.conf'

    at checkExecSyncError (node:child_process:707:11)
    at Object.execFileSync (node:child_process:726:15)
    at /usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/src/pyaircontrol.ts:28:25
    at new Promise (<anonymous>)
    at pyaircontrol.execPromise (/usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/src/pyaircontrol.ts:26:12)
    at pyaircontrol.getData (/usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/src/pyaircontrol.ts:48:17)
    at pyaircontrol.getStatus (/usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/src/pyaircontrol.ts:66:17)
    at CoapClient.getStatus (/usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/src/CoapClient.ts:16:24)
    at CoapClient.getFirmware (/usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/src/CoapClient.ts:20:17)
    at PhilipsAirPlatform.updateFirmware (/usr/lib/node_modules/homebridge-philips-air/src/index.ts:246:63)
[4/11/2021, 8:25:37 PM] Got SIGTERM, shutting down Homebridge...
```

Interestingly enough, I can run aircontrol from an SSH session just fine, without `sudo` or anything.

Any idea under what user is this running and where does it actually try to create `logging.conf`? I tried opening up all permissions on `/home/homebridge`, but that didn't help in any way. 

UPDATE: Using 3.3.0 does not make Homebridge fail startup, but the error is still there and as such the plugin is unusable.

**Comment by NikDevx** [comment]
**Plugin doesn't create any login.conf file**
All error coming from pyaircontrol.py

I think you have permission issues or pyaircontrol.py is not installed correctly
Did you pass all steps from readme?

**Comment by CatalinMustata** [comment]
Yes, I’ve read the traceback and I’ve observed this is created by pyaircontrol - this is why I’m thinking it has something to do with the user under which this is running, since I can run pyaircontrol manually in an ssh terminal and it works fine. 

I’ve installed everything as per instructions. One interesting detail is that installing pyaircontrol without sudo will make it unavailable for this plugin. 

I’ll try to reinstall pyaircontrol tomorrow and see if I can fix it. Otherwise, I’ll start digging through the code. Any pointers would be appreciated.

**Comment by NikDevx** [comment]
Did you run homebridge with sudo permission?

**Comment by CatalinMustata** [comment]
Homebridge is started using `hb-service` which creates a `homebridge` user (and both `hb-service` and `homebridge` run under this user).

I was reading over on the `py-air-control` repo through the issues and some people were complaining that `logging.conf` file is created in the home folder, so I tried giving all permissions on `homebridge`'s home folder but that didn't help.

However, now that I've uninstalled and reinstalled everything it seems to be working. Not sure what triggered it, since the error message is still there, but it is successfully ignored. I think you latest update fixed it (just installed 3.3.1)

One thing I should mention is that using `py-air-control` standalone requires using this fork of CoAP: `git+https://github.com/rgerganov/CoAPthon3`.

My only current issue is that I can't set it to auto mode, which has two causes. First, I can't find a button for that (I can control fan speed through the Home app on my iPhone, including putting it to sleep, but there's no Auto). Secondly, `py-air-control` doesn't seem to manage that either. Setting `om` to anything but `a` works fine though. I will pursue this with the author, but if you have any ideas, please share.

**Comment by NikDevx** [comment]
Read this one https://github.com/NikDevx/homebridge-philips-air/pull/88#issuecomment-808995633

**Comment by CatalinMustata** [comment]
Yeah, that's the one I found in the Home app. What I meant to say is I didn't find that setting in Homebridge's web interface.

I'll see how this works overnight (when my automations should execute), but I think we can close this issue.

Thanks for your help!

**Comment by NikDevx** [comment]
> Yeah, that's the one I found in the Home app. What I meant to say is I didn't find that setting in Homebridge's web interface.
> 
> I'll see how this works overnight (when my automations should execute), but I think we can close this issue.
> 
> Thanks for your help!

You are welcome.
Automation work perfect.

You cannot use turbo speed and auto mode together.
Speed ​​is the first priority and it will disable auto mode in automation.
You should read more about automation setup.

**Comment by CatalinMustata** [comment]
I had to reinstall my whole server after and I'm having a lot of headaches with this again - did some debugging and it looks to me like there's an issue with the user under which all of this runs.

Just to state re-state the things above, I have a standard Homebridge installation under the `homebridge` user. Since this was a fresh installation, I got Python 3.9

I've installed `py-air-control` and @rgerganov's fork of CoAPthon3 (although I had to uninstall the regular CoAPthon3 which comes with that silly logging.conf issue and also doesn't run under Python 3.9). I did this both with sudo and without. Everything works just fine from the terminal.

When I try using the Homebridge plugin, I get an assortment of errors, depending on how I installed `py-air-control`. If it's without `sudo`, then it won't find `pyaircontrol`. If I install it with sudo without overwriting CoAPthon3, it will choke on the `logging.conf` issue. If I overwrite CoAPthon3 (no matter if with or without sudo)... it won't find module `coapthon`.

It's just frustrating at this point...

**Comment by NikDevx** [comment]
I should work without sudo.
 I think you ate have some problem with permissions

**Comment by CatalinMustata** [comment]
Not saying I'm not, but my installation is pretty standard. Any suggestions on where to look to fix permissions would be helpful. Like I said, `airctrl` works just fine from the terminal... only through this plugin does it misbehave.

**Comment by NikDevx** [comment]
Did you install https://github.com/NikDevx/philips-air ?

You should have pyaircontrol.py in global path node_module `(node_modules/philips-air/pyaircontrol.py)`

**Comment by CatalinMustata** [comment]
I didn't even know that existed. I'll try it tomorrow.

**Comment by CatalinMustata** [comment]
Ok, so out of the blue, without me doing anything... it worked. This is very very strange.

I did look for the `philips-air` dependency and I found it in  `/usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/` so I guess that's ok.

However, now I'm getting `Unable to get data for polling: Error: spawnSync python3 ETIMEDOUT.`

I think I'll just quit this as it's too much trouble already. Sorry mate.

**Comment by NikDevx** [comment]
Read this one https://github.com/NikDevx/homebridge-philips-air/issues/169

**Comment by CatalinMustata** [comment]
Yeah, I saw that... it just seems like too finicky / much trouble. I had a look through Homebridge/HomeKit too to learn more about their support for purifiers and there's no easy way to set the bloody thing to Auto Mode for example. Not saying it's your fault, but the whole thing seems like it's kept together with duct tape right now.

It might just be easier for me to write a simple iOS app that allows for Siri control so I can use shortcuts and control my Purifier (I only need it for automation anyway).
