### ISSUE TITLE
AC3829 / 50 not responding - Error: spawnSync python3 ETIMEDOUT

### ISSUE THREAD

**Issue by ProXim86** [NikDevx/homebridge-philips-air#169]
I have a problem.
I connected an AC3829 / 50 air purifier to the system, which works perfectly (on / off, temperature, air purity, humidity) in both Homebridge and HomeKit.
It works like this for 1-2 hours. After that, however, the air purifier itself does not respond to anything, it don't send data from the HomeKit (no longer send data) and not response own CleanHome + application.
It only helps if I unplug the air purifier. Then it works again for a few hours but then it all starts all over again.

What could be the problem? Is the air purifier blocking communication? Has anyone else encountered this problem or the like?
Is there a solution?

Homebridge restart log:
```
Exception: sync timeout
[6/12/2021, 6:43:15 PM] [Philips Air] [Philips Air] Unable to load filter info: Error: Command failed: python3 /usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py --ipaddr 192.168.1.77 --protocol coap --status
Give up on message From None, To ('192.168.1.77', 5683), CON-58070, POST-uf, [Uri-Path: sys, Uri-Path: dev, Uri-Path: sync, ] 61C55DAF...8 bytes
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 123, in <module>
    main()
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 99, in main
    c = CoAPCli(args.ipaddr)
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 15, in __init__
    self._client = CoAPAirClient(host, port, False)
  File "/usr/lib/python3.8/site-packages/pyairctrl/coap_client.py", line 80, in __init__
    self._sync()
  File "/usr/lib/python3.8/site-packages/pyairctrl/coap_client.py", line 96, in _sync
    raise Exception("sync timeout")
Exception: sync timeout

[Philips Air] [Philips Air] Unable to get data for polling: Error: spawnSync python3 ETIMEDOUT.
```

**Comment by NikDevx** [comment]
https://github.com/NikDevx/homebridge-philips-air/issues/162

https://github.com/NikDevx/homebridge-philips-air/issues/167

**Comment by ProXim86** [comment]
> https://github.com/NikDevx/homebridge-philips-air/issues/162
> 
> 
> 
> https://github.com/NikDevx/homebridge-philips-air/issues/167

Thx. Works fine.
