### ISSUE TITLE
This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined

### ISSUE THREAD

**Issue by valentinkrynin** [NikDevx/homebridge-philips-air#173]
firmware does not always have a modelid attribute so I suggest to modify the line
"const name = firmware.modelid;" to "const name = firmware.modelid || 'unknown';" ot something like that.

Firmware object of my purifier:
{
  name: 'AC2729_10',
  version: '8',
  upgrade: '',
  state: 'idle',
  progress: 0,
  statusmsg: '',
  mandatory: false
}

Purifier: AC2729/10
Protocol: http

Error log:
[9/10/2021, 1:52:33 PM] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined. See https://git.io/JtMGR for more info.
[9/10/2021, 1:52:33 PM] [homebridge-philips-air] Error: 
    at Model.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Model.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1986:16)
    at Model.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at AccessoryInformation.Service.updateCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at PhilipsAirPlatform.updateFirmware (/usr/lib/node_modules/homebridge-philips-air/src/index.ts:319:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

https://github.com/NikDevx/homebridge-philips-air/blob/339425f6f0ae72a643276c86450dd0bd3e66b041/src/index.ts#L313
https://github.com/NikDevx/homebridge-philips-air/blob/339425f6f0ae72a643276c86450dd0bd3e66b041/src/index.ts#L318

**Comment by NikDevx** [comment]
All models have a model number
![Снимок экрана 2021-09-10 в 23 37 24](https://user-images.githubusercontent.com/45577540/132914929-da24da0f-6224-415b-9f8b-7b4329537808.png)


And I no longer work with the http protocol after version 2.3.4
